---
title: "SA_Project3"
author: "Haleigh Schwartz"
date: "2024-04-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(skimr)
library(survival)
library(survminer)
library(asaur)
library(broom) 
library(car)
library(nlme)

setwd("/Users/Haleigh/Documents/MSDS/Survival Analysis/RMDs_and_CSVs")

```

```{r}

#initialize empty list
result_list = list()

#set up for loop since doing same thing on all 4 ecosystems
for (i in c("laravel", "npm", "r", "wp")){
  
  #read in data
  meta_i = read_csv(paste("/Users/Haleigh/Documents/MSDS/Survival Analysis/githubSurvival/data/metadata-",i,".csv",sep=""))
  or_i = read_csv(paste("/Users/Haleigh/Documents/MSDS/Survival Analysis/githubSurvival/data/oracle-",i,".csv",sep=""))
  
  #first lowercase the joining columns to make sure they all match
  meta_i = meta_i %>%
  mutate(repo_name = tolower(repo_name))
  or_i = or_i %>%
  mutate(repo = tolower(repo))
  
  #join
  result_list[[i]] = full_join(meta_i, or_i, by=c("repo_name" = "repo"))
  
}

#name individual datasets
lar = result_list[["laravel"]]
npm = result_list[["npm"]]
r = result_list[["r"]]
wp = result_list[["wp"]]


```






















